name: Bug report
description: Report a problem
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen instead?
      placeholder: Please describe clearly, in British English.
    validations:
      required: true
